# This workflow will do a clean install of node dependencies, build the source code and run tests
name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build --if-present
  release:
    name: semantic-release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          # clean out deps so semantic-release doesn't fail
          npm ls --depth=0 | grep -vE '^(npm|├──)' | awk -F@ '{print $1}' | xargs npm rm --save
          npm ls --depth=0 --dev | grep -vE '^(npm|├──)' | awk -F@ '{print $1}' | xargs npm rm --save-dev
          rm package-lock.json
          npm i semantic-release @technologiestiftung/semantic-release-config -D
          npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
